# Copyright Krafter SAS <hey@krafter.io>
# Krafter Proprietary License (see LICENSE file).
{
    'name': 'Pyper Web Theme',
    'category': 'Hidden/Tools',
    'license': 'Other proprietary',
    'description': 'Add pyper web theme with clean back office theme',
    'version': '1.0',
    'author': 'Krafter SAS',
    'installable': True,
    'application': False,
    'maintainer': [
        'Krafter SAS',
    ],
    'website': 'https://krafter.io',
    'depends': [
        'web',
        'base',
        'base_automation',
        'base_setup',
        'mail',
        'pyper',
        'pyper_drawer',
        'pyper_fonts_phosphor',
        'pyper_saas',
        'pyper_command_search',
        'pyper_control_panel',
        'pyper_overlay_menu',
        'pyper_activity',
    ],
    'data': [
        'views/res_config_settings_views.xml',
        'views/mail_message_views.xml',
    ],
    'assets': {
        'web._assets_primary_variables': [
            ('before', 'pyper/static/src/**/*.variables.scss', 'pyper_web_theme/static/src/**/*.variables.scss'),
            ('before', 'pyper/static/src/scss/primary_variables.scss', 'pyper_web_theme/static/src/scss/primary_variables.scss'),
        ],
        'web._assets_secondary_variables': [
            ('before', 'pyper/static/src/scss/secondary_variables.scss', 'pyper_web_theme/static/src/scss/secondary_variables.scss'),
        ],
        'web.assets_frontend': [
            "pyper_web_theme/static/src/scss/style.scss"
        ],
        'web._assets_frontend_helpers': [
            ('prepend', 'web/static/src/scss/bootstrap_overridden.scss'),
            ('prepend', 'web_editor/static/src/scss/bootstrap_overridden.scss'),
            ('prepend', 'pyper/static/src/scss/bootstrap_overridden.scss'),
            ('prepend', 'pyper_web_theme/static/src/scss/bootstrap_overridden.scss'),
        ],
        'web._assets_backend_helpers': [
            ('before', 'pyper/static/src/scss/bootstrap_overridden.scss', 'pyper_web_theme/static/src/scss/bootstrap_overridden.scss'),
        ],
        'web.assets_backend': [
            ('prepend', 'pyper_fonts_phosphor/static/src/scss/phosphor-regular.scss'),
            ('prepend', 'pyper_fonts_phosphor/static/src/scss/phosphor-light.scss'),
            ('prepend', 'pyper_fonts_phosphor/static/src/scss/phosphor-fill.scss'),
            ('after', 'web/static/src/views/list/list_controller.xml','pyper_web_theme/static/src/views/list/list_controller.xml'),
            ('after', 'web/static/src/views/list/list_renderer.scss','pyper_web_theme/static/src/views/list/list_renderer.scss'),
            ('after', 'web/static/src/views/list/list_renderer.xml','pyper_web_theme/static/src/views/list/list_renderer.xml'),
            ('after', 'web/static/src/views/pivot/pivot_renderer.xml', 'pyper_web_theme/static/src/views/pivot/pivot_renderer.xml'),
            ('after', 'mail/static/src/views/web/form/form_renderer.scss', 'pyper_web_theme/static/src/mail/form_renderer.scss'),
            ('before', 'mail/static/src/scss/variables/derived_variables.scss','pyper_web_theme/static/src/mail/derived_variables.scss'),
            ('replace', 'web/static/src/views/form/form_controller.scss','pyper_web_theme/static/src/views/form/form_controller.scss'),
            ('after', 'mail/static/src/core/web/chatter.xml', 'pyper_web_theme/static/src/core/web/chatter.xml'),
            ('after', 'mail/static/src/core/common/date_section.xml', 'pyper_web_theme/static/src/core/web/date_section.xml'),
            ('after', 'mail/static/src/core/common/message.xml', 'pyper_web_theme/static/src/core/web/message.xml'),
            ('after', 'web/static/src/views/form/form_status_indicator/form_status_indicator.xml', 'pyper_web_theme/static/src/views/form/form_status_indicator/form_status_indicator.xml'),
            ('after', 'mail/static/src/**/web/**/*', 'pyper_web_theme/static/src/utilities/**/*'),
            ('after', 'web/static/src/views/form/form_controller.xml','pyper_web_theme/static/src/views/form/form_controller.xml'),
            ('after', 'mail/static/src/core/web/activity_button.xml', 'pyper_web_theme/static/src/core/web/activity_button.xml'),
            ('after', 'web/static/src/search/search_bar/search_bar.xml', 'pyper_web_theme/static/src/search/search_bar/search_bar.xml'),
            ('after', 'web/static/src/views/kanban/kanban_column_progressbar.scss','pyper_web_theme/static/src/views/kanban/kanban_column_progressbar.scss'),
            ('replace', 'mail/static/src/core/web/suggested_recipient.xml', 'pyper_web_theme/static/src/mail/web/suggested_recipient.xml'),
            ('after', 'mail/static/src/core/common/composer.xml', 'pyper_web_theme/static/src/mail/common/composer.xml'),
            'pyper_web_theme/static/lib/odoo_ui_icons/style.css',
            'pyper_web_theme/static/src/scss/style.scss',
            'pyper_web_theme/static/src/views/**/*',
            'pyper_web_theme/static/src/webclient/**/*',
            "pyper_web_theme/static/src/core/web/thread_service_patch.js",
            ('after', 'mail/static/src/core/web/follower_list.xml', 'pyper_web_theme/static/src/mail/web/follower_list.xml'),
        ],
    },
}
